import {
  Building2,
  ShieldCheck,
  BadgeCheck,
  CreditCard,
  Lock,
  Database,
} from "lucide-react";

const complianceItems = [
  {
    icon: Building2,
    title: "NABH — National Accreditation Board for Hospitals",
    description:
      "Discharge documentation aligned with NABH clinical documentation standards. Mandatory fields are automatically populated for accreditation.",
    badge: "NABH Compliance",
  },
  {
    icon: ShieldCheck,
    title: "MCI/NMC Medical Council Compliance",
    description:
      "Structured discharge summaries that satisfy Medical Council of India and NMC (National Medical Commission) documentation requirements.",
    badge: "AIIMS Compliance",
  },
  {
    icon: BadgeCheck,
    title: "JCI Accreditation Support",
    description:
      "Complete, timestamped and digitally signed documentation supporting JCI accreditation audits.",
    badge: "JCI Ready",
  },
  {
    icon: CreditCard,
    title: "Insurance & TPA Integration",
    description:
      "ICD-10 coded summaries that reduce claim rejections and accelerate insurance approvals. Compatible with CGHS, ESIC, and private TPAs.",
    badge: "TPA Ready",
  },
  {
    icon: Lock,
    title: "India Data Residency & Security",
    description:
      "Patient information remains secure with India data center hosting and ISO 27001 certified enterprise-grade security controls.",
    badge: "ISO 27001",
  },
  {
    icon: Database,
    title: "ABDM / Health Records Exchange Ready",
    description:
      "Generate structured summaries compatible with Ayushman Bharat Digital Mission (ABDM) and national health information exchange.",
    badge: "ABDM Ready",
  },
];

const ComplianceSection = () => {
  return (
    <section
      id="compliance"
      className="bg-[#2E4168] py-24"
    >
      <div className="mx-auto max-w-7xl px-6 lg:px-8">
        {/* Heading */}

        <span className="text-sm font-semibold uppercase tracking-[0.25em] text-[#C9912A]">
          Regulatory Standards
        </span>

        <h2 className="mt-4 text-4xl font-black leading-tight text-white md:text-5xl">
          Built for India
          <br />
          Regulatory Compliance
        </h2>

        <p className="mt-6 max-w-3xl text-lg leading-8 text-slate-300">
          Every discharge summary generated by GudMed follows Indian
          healthcare documentation standards (ABDM, NABH, CGHS), helping hospitals
          maintain compliance while reducing manual effort.
        </p>

        {/* Cards */}

        <div className="mt-16 grid gap-6 md:grid-cols-2 xl:grid-cols-3">
          {complianceItems.map((item) => {
            const Icon = item.icon;

            return (
              <div
                key={item.title}
                className="rounded-2xl border border-white/10 bg-white/5 p-7 transition duration-300 hover:border-[#C9912A]/50 hover:bg-white/10"
              >
                {/* Icon */}

                <div className="mb-6 flex h-14 w-14 items-center justify-center rounded-xl bg-[#C9912A]/10 text-[#C9912A]">
                  <Icon size={28} />
                </div>

                {/* Title */}

                <h3 className="text-xl font-semibold text-white">
                  {item.title}
                </h3>

                {/* Description */}

                <p className="mt-4 leading-7 text-slate-300">
                  {item.description}
                </p>

                {/* Badge */}

                <span className="mt-6 inline-block rounded-full border border-[#C9912A]/30 bg-[#C9912A]/10 px-4 py-2 text-sm font-semibold text-[#C9912A]">
                  {item.badge}
                </span>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
};

export default ComplianceSection;